version: '3.8'

services:
  jenkins:
    build:
      context: ./jenkins             # Uses updated Dockerfile with Trivy + kubectl
      dockerfile: Dockerfile
    container_name: jenkins
    user: root
    ports:
      - "8081:8080"                  # Jenkins UI
      - "50000:50000"                # Jenkins agent communication
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Docker CLI access
      - /home/ubuntu/.kube/config:/root/.kube/config  # Kubernetes config
      - /home/ubuntu/.minikube:/home/jenkins/.minikube  # Minikube cache for Jenkins
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

  springboot-app:
    image: venkatesh384/jenkins-demo:latest
    container_name: jenkins-demo
    ports:
      - "8080:8080"                  # Expose Spring Boot app (for local test only)

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"                  # SonarQube UI
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions

volumes:
  jenkins_home:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
