version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8081:8080"      # Changed to 8081 to avoid conflict
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

  springboot-app:
    image: jenkins-demo
    container_name: jenkins-demo
    ports:
      - "8080:8080"      # Spring Boot app

volumes:
  jenkins_home:
