apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: springboot-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30008   # External port you can access on EC2 or Minikube
