apiVersion: v1
kind: Service
metadata:
  name: jenkins-demo-service
  namespace: dev
spec:
  selector:
    app: jenkins-demo
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
