apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: dev
spec:
  type: LoadBalancer   # ✅ Changed from NodePort
  selector:
    app: springboot-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
