apiVersion: v1
kind: Service
metadata:
  name: springboot-app
  namespace: dev
spec:
  type: NodePort
  selector:
    app: springboot-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
