apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: dev  # 👈 Optional, but recommended for consistency
spec:
  selector:
    app: springboot-app  # 👈 Must match Deployment label
  ports:
  - port: 80
    targetPort: 8080
  type: NodePort
