apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: dev
spec:
  selector:
    app: spring
  ports:
    - protocol: TCP
      port: 8080
      targetPort: {{ .Values.springApp.port }}
