apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: spring
  ports:
    - protocol: TCP
      port: 8080
      targetPort: {{ .Values.springApp.port }}
      nodePort: 30036   # Optional: Set static NodePort or let K8s assign dynamically
